name: CI/CD for Calculator App

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js (version 16)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Navigate to Project Directory (if needed)
      run: cd path/to/your/project

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: echo "No tests available" 

    - name: Build Docker Image
      run: docker build -t calculator-js .

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker tag calculator-js:latest $DOCKER_USERNAME/calculator-js:latest
        docker push $DOCKER_USERNAME/calculator-js:latest
