name: CI/CD for Calculator App

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: echo "No tests available" 

    - name: Build Docker Image
      run: docker build -t calculator-js .

    - name: Push to Docker Hub
      run: |
        echo "dckr_pat_71Vg8M_y3o7fZo25tpFoiDjGibU" | docker login -u "maiatef066" --password-stdin
        docker tag calculator-js:latest maiatef066/calculator-js:latest
        docker push maiatef066/calculator-js:latest
